version: '3'
services:
  pgsql:
    image: postgres:13
    ports:
        - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
        PGPASSWORD: '${DB_PASSWORD:-secret}'
        POSTGRES_DB: '${DB_DATABASE}'
        POSTGRES_USER: '${DB_USERNAME}'
        POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
        - 'barrentix-postgresql:/var/lib/postgresql/data'
    networks:
        - barrentix
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]

networks:
    barrentix:
        driver: bridge
volumes:

    barrentix-postgresql:
        driver: local